name: Node.js CI

on:
  push:
    branches: [dev]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Installing dependencies
        run: npm ci
      - name: Running Eslint
        run: npm run eslint
      - name: Running Stylelint
        run: npm run stylelint
      - name: Running Prettier
        run: npm run prettier